import express from "express";
import cors from "cors";
import dotenv from "dotenv";
import doctorRoutes from "./routes/doctorRoutes";
import patientRoutes from "./routes/patientRoutes";
import appointmentRoutes from "./routes/appointmentRoutes";
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.use("/api/doctors", doctorRoutes);
app.use("/api/patients", patientRoutes);
app.use("/api/appointments", appointmentRoutes);
const port = process.env.PORT || 3001;
app.listen(port, () => console.log(`api ${port}`));
